dist: bionic

sudo: false

language: cpp

compiler: gcc

addons:
    apt:
        packages:
            - cmake
            - lcov
            - cppcheck

before_script:
    - ./travis/before_script.sh

script:
    - ./travis/script.sh

after_script:
    - ./travis/after_script.sh